### ISSUE TITLE
Version issues

### ISSUE THREAD

**Issue by hegelstad** [ismayilmalik/react-native-checkbox-heaven#7]
Hi, this doesn't work when following the installation.

The package downloaded from npm contains an old version of CheckBox.js without the newest PR to fix proptypes.

Workaround:

`npm install git+https://github.com/ismayilmalik/react-native-checkbox-heaven.git --save`

**Comment by jskidd3** [comment]
@hegelstad Is there a more permanent solution than this? I have to re-run this command each time I use `react-native link`.

**Comment by hegelstad** [comment]
@jskidd3 check that the dep entry in package.json is changed to the link above!

**Comment by ismanf** [comment]
I have updated npm repo, thanks!
