### ISSUE TITLE
undefined is not an object (evaluating 'PropTypes.func')

### ISSUE THREAD

**Issue by r3wt** [ismayilmalik/react-native-checkbox-heaven#8]
hi, i just installed your library, restarted the packager and attempted to use the checkbox in my view. instead, i am greeted by this error from the development server. i am using latest version of react native and latest version of react 16

**Comment by oscaralanpierce** [comment]
It's because after React 15.5, PropTypes was extracted to the `'prop-types'` package.

**Comment by oscaralanpierce** [comment]
Looks like it's fixed on master but not on the latest release. @r3wt

**Comment by oscaralanpierce** [comment]
Oh - and it's a PITA, btw, but you can actually manually fix this at least in your local dev environment with a one-line change to react-native-checkbox-heaven 0.1.3 - just go to src/CheckBox.js and change 
```javascript
const { ProcTypes } = React
```
to
```javascript
import ProcTypes from 'proc-types'
```
within your node_modules directory.

**Comment by ismayilmalik** [comment]
I have updated npm repo, Thanks all!
